# Generated by Django 2.2.2 on 2019-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
