# Generated by Django 2.2.2 on 2019-07-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190703_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, default=None, upload_to='files'),
        ),
    ]
